<?php

namespace Database\Seeders;

use App\Models\SystemSetting;
use Illuminate\Database\Seeder;

class SystemSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // ========== THÔNG TIN CÔNG TY ==========
            [
                'group' => 'company',
                'key' => 'company_name',
                'value' => 'Binhan Ambulance',
                'type' => 'text',
                'description' => 'Tên công ty',
                'order' => 1,
                'is_public' => true,
            ],
            [
                'group' => 'company',
                'key' => 'company_short_name',
                'value' => 'Binhan',
                'type' => 'text',
                'description' => 'Tên viết tắt',
                'order' => 2,
                'is_public' => true,
            ],
            [
                'group' => 'company',
                'key' => 'company_slogan',
                'value' => 'Chăm sóc sức khỏe - Tận tâm phục vụ',
                'type' => 'text',
                'description' => 'Slogan công ty',
                'order' => 3,
                'is_public' => true,
            ],
            [
                'group' => 'company',
                'key' => 'company_description',
                'value' => 'Hệ thống quản lý xe cấp cứu chuyên nghiệp',
                'type' => 'textarea',
                'description' => 'Mô tả công ty',
                'order' => 4,
                'is_public' => true,
            ],
            [
                'group' => 'company',
                'key' => 'company_email',
                'value' => 'contact@binhan.com',
                'type' => 'email',
                'description' => 'Email liên hệ',
                'order' => 5,
                'is_public' => true,
            ],
            [
                'group' => 'company',
                'key' => 'company_phone',
                'value' => '1900 xxxx',
                'type' => 'text',
                'description' => 'Số điện thoại',
                'order' => 6,
                'is_public' => true,
            ],
            [
                'group' => 'company',
                'key' => 'company_hotline',
                'value' => '0901 234 567',
                'type' => 'text',
                'description' => 'Hotline',
                'order' => 7,
                'is_public' => true,
            ],
            [
                'group' => 'company',
                'key' => 'company_address',
                'value' => 'Hà Nội, Việt Nam',
                'type' => 'textarea',
                'description' => 'Địa chỉ công ty',
                'order' => 8,
                'is_public' => true,
            ],
            [
                'group' => 'company',
                'key' => 'company_tax_code',
                'value' => '',
                'type' => 'text',
                'description' => 'Mã số thuế',
                'order' => 9,
                'is_public' => false,
            ],
            [
                'group' => 'company',
                'key' => 'company_website',
                'value' => 'https://binhan.com',
                'type' => 'url',
                'description' => 'Website',
                'order' => 10,
                'is_public' => true,
            ],

            // ========== GIAO DIỆN ==========
            [
                'group' => 'appearance',
                'key' => 'site_name',
                'value' => 'Binhan Ambulance',
                'type' => 'text',
                'description' => 'Tên website (hiển thị trên tab trình duyệt)',
                'order' => 1,
                'is_public' => true,
            ],
            [
                'group' => 'appearance',
                'key' => 'site_logo',
                'value' => '',
                'type' => 'image',
                'description' => 'Logo chính (PNG, tối đa 2MB)',
                'order' => 2,
                'is_public' => true,
            ],
            [
                'group' => 'appearance',
                'key' => 'site_favicon',
                'value' => '',
                'type' => 'image',
                'description' => 'Favicon (ICO/PNG 32x32)',
                'order' => 3,
                'is_public' => true,
            ],
            [
                'group' => 'appearance',
                'key' => 'primary_color',
                'value' => '#667eea',
                'type' => 'color',
                'description' => 'Màu chủ đạo',
                'order' => 4,
                'is_public' => true,
            ],
            [
                'group' => 'appearance',
                'key' => 'secondary_color',
                'value' => '#764ba2',
                'type' => 'color',
                'description' => 'Màu phụ',
                'order' => 5,
                'is_public' => true,
            ],
            [
                'group' => 'appearance',
                'key' => 'login_background',
                'value' => '',
                'type' => 'image',
                'description' => 'Hình nền trang login',
                'order' => 6,
                'is_public' => true,
            ],
            [
                'group' => 'appearance',
                'key' => 'font_family',
                'value' => 'Inter',
                'type' => 'select',
                'options' => json_encode(['Inter', 'Roboto', 'Open Sans', 'Montserrat', 'Poppins']),
                'description' => 'Font chữ hệ thống',
                'order' => 7,
                'is_public' => true,
            ],
            [
                'group' => 'appearance',
                'key' => 'records_per_page',
                'value' => '15',
                'type' => 'select',
                'options' => json_encode(['10', '15', '25', '50', '100']),
                'description' => 'Số bản ghi mỗi trang',
                'order' => 8,
                'is_public' => false,
            ],

            // ========== NGÔN NGỮ & ĐỊNH DẠNG ==========
            [
                'group' => 'language',
                'key' => 'default_language',
                'value' => 'vi',
                'type' => 'select',
                'options' => json_encode(['vi' => 'Tiếng Việt', 'en' => 'English']),
                'description' => 'Ngôn ngữ mặc định',
                'order' => 1,
                'is_public' => true,
            ],
            [
                'group' => 'language',
                'key' => 'timezone',
                'value' => 'Asia/Ho_Chi_Minh',
                'type' => 'select',
                'options' => json_encode(['Asia/Ho_Chi_Minh' => 'Việt Nam (GMT+7)', 'Asia/Bangkok' => 'Bangkok (GMT+7)', 'Asia/Singapore' => 'Singapore (GMT+8)']),
                'description' => 'Múi giờ',
                'order' => 2,
                'is_public' => false,
            ],
            [
                'group' => 'language',
                'key' => 'date_format',
                'value' => 'd/m/Y',
                'type' => 'select',
                'options' => json_encode(['d/m/Y' => 'DD/MM/YYYY', 'm/d/Y' => 'MM/DD/YYYY', 'Y-m-d' => 'YYYY-MM-DD']),
                'description' => 'Định dạng ngày',
                'order' => 3,
                'is_public' => true,
            ],
            [
                'group' => 'language',
                'key' => 'time_format',
                'value' => 'H:i',
                'type' => 'select',
                'options' => json_encode(['H:i' => '24 giờ (13:00)', 'h:i A' => '12 giờ (01:00 PM)']),
                'description' => 'Định dạng giờ',
                'order' => 4,
                'is_public' => true,
            ],
            [
                'group' => 'language',
                'key' => 'currency',
                'value' => 'VND',
                'type' => 'text',
                'description' => 'Đơn vị tiền tệ',
                'order' => 5,
                'is_public' => true,
            ],
            [
                'group' => 'language',
                'key' => 'currency_symbol',
                'value' => '₫',
                'type' => 'text',
                'description' => 'Ký hiệu tiền tệ',
                'order' => 6,
                'is_public' => true,
            ],
            [
                'group' => 'language',
                'key' => 'currency_position',
                'value' => 'after',
                'type' => 'select',
                'options' => json_encode(['before' => 'Trước số (₫100)', 'after' => 'Sau số (100₫)']),
                'description' => 'Vị trí ký hiệu tiền',
                'order' => 7,
                'is_public' => true,
            ],
            [
                'group' => 'language',
                'key' => 'decimal_places',
                'value' => '0',
                'type' => 'select',
                'options' => json_encode(['0' => '0', '2' => '2']),
                'description' => 'Số chữ số thập phân',
                'order' => 8,
                'is_public' => true,
            ],
            [
                'group' => 'language',
                'key' => 'thousand_separator',
                'value' => ',',
                'type' => 'select',
                'options' => json_encode([',' => 'Dấu phẩy (,)', '.' => 'Dấu chấm (.)', ' ' => 'Khoảng trắng']),
                'description' => 'Phân cách hàng nghìn',
                'order' => 9,
                'is_public' => true,
            ],

            // ========== NGHIỆP VỤ ==========
            [
                'group' => 'business',
                'key' => 'free_kilometers',
                'value' => '10',
                'type' => 'number',
                'description' => 'Số km miễn phí',
                'order' => 1,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'price_per_km',
                'value' => '15000',
                'type' => 'number',
                'description' => 'Giá mỗi km thêm (VND)',
                'order' => 2,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'vat_rate',
                'value' => '10',
                'type' => 'number',
                'description' => 'Thuế VAT (%)',
                'order' => 3,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'service_fee',
                'value' => '0',
                'type' => 'number',
                'description' => 'Phí dịch vụ (%)',
                'order' => 4,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'waiting_fee_per_hour',
                'value' => '50000',
                'type' => 'number',
                'description' => 'Giá tiền chờ mỗi giờ (VND)',
                'order' => 5,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'free_waiting_time',
                'value' => '30',
                'type' => 'number',
                'description' => 'Thời gian chờ miễn phí (phút)',
                'order' => 6,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'auto_calculate_fee',
                'value' => '1',
                'type' => 'checkbox',
                'description' => 'Tự động tính tiền',
                'order' => 7,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'require_approval',
                'value' => '0',
                'type' => 'checkbox',
                'description' => 'Yêu cầu phê duyệt chuyến đi',
                'order' => 8,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'allow_edit_after_save',
                'value' => '1',
                'type' => 'checkbox',
                'description' => 'Cho phép chỉnh sửa sau khi lưu',
                'order' => 9,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'shift_start_time',
                'value' => '07:00',
                'type' => 'time',
                'description' => 'Giờ bắt đầu ca',
                'order' => 10,
                'is_public' => false,
            ],
            [
                'group' => 'business',
                'key' => 'shift_end_time',
                'value' => '19:00',
                'type' => 'time',
                'description' => 'Giờ kết thúc ca',
                'order' => 11,
                'is_public' => false,
            ],

            // ========== BẢO MẬT ==========
            [
                'group' => 'security',
                'key' => 'session_timeout',
                'value' => '120',
                'type' => 'number',
                'description' => 'Timeout session (phút)',
                'order' => 1,
                'is_public' => false,
            ],
            [
                'group' => 'security',
                'key' => 'max_login_attempts',
                'value' => '5',
                'type' => 'number',
                'description' => 'Số lần đăng nhập sai tối đa',
                'order' => 2,
                'is_public' => false,
            ],
            [
                'group' => 'security',
                'key' => 'lockout_duration',
                'value' => '15',
                'type' => 'number',
                'description' => 'Thời gian khóa tài khoản (phút)',
                'order' => 3,
                'is_public' => false,
            ],
            [
                'group' => 'security',
                'key' => 'min_password_length',
                'value' => '8',
                'type' => 'number',
                'description' => 'Độ dài mật khẩu tối thiểu',
                'order' => 4,
                'is_public' => false,
            ],
            [
                'group' => 'security',
                'key' => 'require_special_char',
                'value' => '0',
                'type' => 'checkbox',
                'description' => 'Yêu cầu ký tự đặc biệt trong mật khẩu',
                'order' => 5,
                'is_public' => false,
            ],
            [
                'group' => 'security',
                'key' => 'require_number',
                'value' => '1',
                'type' => 'checkbox',
                'description' => 'Yêu cầu số trong mật khẩu',
                'order' => 6,
                'is_public' => false,
            ],
            [
                'group' => 'security',
                'key' => 'require_uppercase',
                'value' => '0',
                'type' => 'checkbox',
                'description' => 'Yêu cầu chữ hoa trong mật khẩu',
                'order' => 7,
                'is_public' => false,
            ],
            [
                'group' => 'security',
                'key' => 'allow_remember_me',
                'value' => '1',
                'type' => 'checkbox',
                'description' => 'Cho phép ghi nhớ đăng nhập',
                'order' => 8,
                'is_public' => false,
            ],

            // ========== BACKUP & BẢO TRÌ ==========
            [
                'group' => 'maintenance',
                'key' => 'auto_backup',
                'value' => '0',
                'type' => 'checkbox',
                'description' => 'Tự động backup',
                'order' => 1,
                'is_public' => false,
            ],
            [
                'group' => 'maintenance',
                'key' => 'backup_frequency',
                'value' => 'daily',
                'type' => 'select',
                'options' => json_encode(['daily' => 'Hàng ngày', 'weekly' => 'Hàng tuần', 'monthly' => 'Hàng tháng']),
                'description' => 'Tần suất backup',
                'order' => 2,
                'is_public' => false,
            ],
            [
                'group' => 'maintenance',
                'key' => 'retain_backups_days',
                'value' => '30',
                'type' => 'number',
                'description' => 'Giữ backup trong bao nhiêu ngày',
                'order' => 3,
                'is_public' => false,
            ],
            [
                'group' => 'maintenance',
                'key' => 'maintenance_mode',
                'value' => '0',
                'type' => 'checkbox',
                'description' => 'Chế độ bảo trì',
                'order' => 4,
                'is_public' => false,
            ],
            [
                'group' => 'maintenance',
                'key' => 'maintenance_message',
                'value' => 'Hệ thống đang bảo trì, vui lòng quay lại sau.',
                'type' => 'textarea',
                'description' => 'Thông báo bảo trì',
                'order' => 5,
                'is_public' => true,
            ],

            // ========== HỆ THỐNG ==========
            [
                'group' => 'system',
                'key' => 'debug_mode',
                'value' => '0',
                'type' => 'checkbox',
                'description' => 'Chế độ debug (chỉ dùng khi development)',
                'order' => 1,
                'is_public' => false,
            ],
            [
                'group' => 'system',
                'key' => 'log_level',
                'value' => 'info',
                'type' => 'select',
                'options' => json_encode(['debug' => 'Debug', 'info' => 'Info', 'warning' => 'Warning', 'error' => 'Error']),
                'description' => 'Mức độ log',
                'order' => 2,
                'is_public' => false,
            ],
            [
                'group' => 'system',
                'key' => 'max_upload_size',
                'value' => '10',
                'type' => 'number',
                'description' => 'Kích thước file upload tối đa (MB)',
                'order' => 3,
                'is_public' => false,
            ],
            [
                'group' => 'system',
                'key' => 'allowed_file_types',
                'value' => 'jpg,jpeg,png,pdf,doc,docx,xls,xlsx',
                'type' => 'text',
                'description' => 'Loại file cho phép upload (phân cách bằng dấu phẩy)',
                'order' => 4,
                'is_public' => false,
            ],
            [
                'group' => 'system',
                'key' => 'enable_cache',
                'value' => '1',
                'type' => 'checkbox',
                'description' => 'Bật cache hệ thống',
                'order' => 5,
                'is_public' => false,
            ],
            [
                'group' => 'system',
                'key' => 'cache_duration',
                'value' => '60',
                'type' => 'number',
                'description' => 'Thời gian cache (phút)',
                'order' => 6,
                'is_public' => false,
            ],
            [
                'group' => 'system',
                'key' => 'log_retention_days',
                'value' => '90',
                'type' => 'number',
                'description' => 'Số ngày giữ log',
                'order' => 7,
                'is_public' => false,
            ],
        ];

        foreach ($settings as $setting) {
            SystemSetting::firstOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('System settings seeded successfully!');
    }
}
